#!/bin/sh
$HOME/.platformio/packages/tool-openocd/bin/openocd -f "interface/stlink-v2.cfg" -f "target/nrf51.cfg" -c "program $HOME/.platformio/packages/framework-mbed/targets/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_8_0_0/s110_nrf51822_8.0.0_softdevice.hex verify reset; shutdown;"
